### ISSUE TITLE
Support for RabbitMQ.Client v6.x

### ISSUE THREAD

**Issue by paolobriones** [steffenlyng/serilog-sinks-rabbitmq#102]
**Unhandled exception. System.MissingMethodException: Method not found: 'Void RabbitMQ.Client.ConnectionFactory.set_Protocol(RabbitMQ.Client.IProtocol)'.**

This exception is thrown using the Serilog.Sinks.RabbitMQ 3.0.6 and RabbitMQ.Client 6.0.0

**Comment by steffenlyng** [comment]
@paolobriones please provide some more information, like a stack trace and maybe an example that reproduces the error.

**Comment by steffenlyng** [comment]
This is included in the upcoming 4.0.0 release.

**Comment by niwrA** [comment]
Let me know if / when I can try a pre-release - I need this one!

**Comment by niwrA** [comment]
I went ahead and forked this and created a working version myself. Let me know if you want this as a PR. I skipped the Protocol functionality, updated the Framework to minimum 462 and netstandard 2.0 and added appnetcore2.0, as that one can be preferred for those just working with core - (sometimes many) fewer external packages needed.

**Comment by irfansagir** [comment]
> This is included in the upcoming 4.0.0 release.

I have the same error. When do you intend to release the 4.0 version?

**Comment by alan994** [comment]
@steffenlyng  I'm also blocked by this one. Is it possible to find out release date?

**Comment by cmvcamacho** [comment]
Hello @steffenlyng ,

Thanks for all your hard work.
Do you have any timeline to release this new version?

Carlos Camacho

**Comment by steffenlyng** [comment]
Hi all -- I'll get a version out during the weekend.

**Comment by steffenlyng** [comment]
@paolobriones @cmvcamacho @irfansagir @niwrA I have just pushed a pre-release for v6.0.0 of RabbitMQ.Client. Please let me know if you experience any issues with it.

I'm switching to a new versioning scheme, so the version of Serilog.Sinks.RabbitMQ will match RabbitMQ.Client in the future. Therefore this slightly older version of the 6+ library from RabbitMQ.Client.

If it looks okay, I will create updated versions for later versions, and new features.

**Comment by niwrA** [comment]
Hi @steffenlyng,

Thanks, just replaced my custom version with the pre-release and it works as advertised. 

I think that kind of versioning is a a good approach, so you can pick the right sink with the right version of rabbitmq, should you need something that requires older functionality targeting an older framework etc. Not that common, but it happens (it is something I came across when using the RabbitMQ client to communicate from older 4.61 software, in which case I needed the 6.0.0.0 client rather than the latest 6.0.21.0 for instance).

Kind regards,
Arwin

**Comment by steffenlyng** [comment]
Since there have been no problems reported, I will prepare the 6.0.0 release

**Comment by g-zx** [comment]
Hi @steffenlyng,

Any updates on this?

**Comment by steffenlyng** [comment]
[6.0.0 is now released on nuget](https://www.nuget.org/packages/Serilog.Sinks.RabbitMQ/6.0.0)
