### ISSUE TITLE
Create stress test

### ISSUE THREAD

**Issue by huan086** [steffenlyng/serilog-sinks-rabbitmq#78]
**Is your feature request related to a problem? Please describe.**
Current code is not following RabbitMQ client's recommended usage. There is a risk that in high concurrency scenario, the logs will get corrupted. However, it is unclear whether Serilog itself has any built-in synchronization mechanism that makes synchronizing usage of RabbitMQ client unneeded

**Describe the solution you'd like**
Create a stress test docker environment to show that the current code breaks, or doesn't

**Describe alternatives you've considered**
Just follow the recomended RabbitMQ client pattern without test

**Additional context**
https://www.rabbitmq.com/dotnet-api-guide.html#model-sharing

**Comment by steffenlyng** [comment]
@huan086 With the knowledge that this Sink is being used in production in a high-volume setting, and not hearing any issues about the scenario that is described, it is my assesment that it is not something that needs to be adressed at this time. It's true that we could prove that the Sink performs in accords with the RabbitMq.Client specifications, but I doubt that has any value with respect to yours and my time.
