### ISSUE TITLE
Serilog.Sinks.RabbitMQ.RabbitMQClient not properly initialized

### ISSUE THREAD

**Issue by misky1986** [steffenlyng/serilog-sinks-rabbitmq#91]
**Describe the bug**
Serilog.Sinks.RabbitMQ.RabbitMQClient not properly initialized after I updated Serilog.Sinks.RabbitMQ from version 3.0.0 to version 3.0.3.

Even though I have initialized RabbitMQClientConfiguration as I have done earlier, there seems to be an error in the Serilog.Sinks.RabbitMQ.RabbitMQClient which makes the class not to be initialized properly.

As showed in the section "How to reproduce" I expect the connection should point to the host called "remote-server" but instead in is initialize with the value "localhost" as shown on the two pictures I have attached.

**To Reproduce**
1. Create a Console application in .Net Core or .Net standard
2. Paste in the following instead of the main method
`
        static void Main(string[] args)
        {
            string UserName = "rabbitmq-test-user";
            string Password = "rabbitmq-test-password";
            string HostName = "remote-server";                        
            string routingKey = "testqueue";            

            int port = 5672;

            Console.WriteLine("Hello this is the sender application!");

            var config = new RabbitMQClientConfiguration
            {
                Port = port,
                Username = UserName,
                DeliveryMode = Serilog.Sinks.RabbitMQ.RabbitMQDeliveryMode.Durable,
                Password = Password,
                RouteKey = routingKey                
            };

            config.Hostnames.Add(HostName);

            Logger logger = new LoggerConfiguration()
                .WriteTo.RabbitMQ((clientConfiguration, sinkConfiguration) =>
                {
                    clientConfiguration.From(config);
                    sinkConfiguration.TextFormatter = new JsonFormatter();
                })
                .MinimumLevel.Verbose()
                .CreateLogger();

            for (int i = 0; i < 4; i++)
            {
                logger.Warning($"{i}. This is a test warning log");
            }
        }
`
3. run the application.

**Expected behavior**
No log messages are pushed to the RabbitMQ queue called "testqueue"

**Screenshots**
![RabbitMQConnectionFactory-bug](https://user-images.githubusercontent.com/2043068/62686442-0c71ef00-b9c5-11e9-8d73-a59b89c2c719.PNG)
![RabbitMQ-bug](https://user-images.githubusercontent.com/2043068/62686444-0c71ef00-b9c5-11e9-8681-6d8417153224.PNG)

**Operating System and Software (please complete the following information):**
 - OS: Windows 10 Enterprise x64

**Comment by sonicjolt** [comment]
@misky1986 Thank you for the bug.

It seems to be missing a specification of what Exchange you are sending your messages to. You have only specified a routing key, which is what can be used to 'route' messages to a specific queue.

Could that be what is going wrong ?

**Comment by misky1986** [comment]
@sonicjolt Your welcome. 

And by the way. Thanks a lot for your cool nuget package. It is awesome :)

Yes, maybe I should have written that in the bug description as well.
The default behavior in RabbitMQ is, that if you leave the exchange property empty (""), RabbitMQ is going to use the default exchange to bind to the queue.
For this to work, it is important that the routing key does match the queue name. In that case the default exchange is used.

I learned about the default behavior at the following link: https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default

I think it is something else that is the problem.

**Comment by cognitive-arch** [comment]
Hey Im facing the same problem. I made a new .net core web project and configured the skin as mentioned in this repo but its not logging anything on RabbitMQ. 
Im using this version Serilog.Sinks.RabbitMQ:3.0.6.

Below is my configuration.
 ```
Logger logger = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .WriteTo.RabbitMQ((clientConfiguration, sinkConfiguration) =>
            {
                clientConfiguration.Port = 5672;
                clientConfiguration.DeliveryMode = RabbitMQDeliveryMode.Durable;
                clientConfiguration.Exchange = "serilog-sink-exchange";
                clientConfiguration.Username = "guest";
                clientConfiguration.Password = "guest";
                clientConfiguration.ExchangeType = "fanout";
                clientConfiguration.Hostnames.Add(HostName);
                sinkConfiguration.TextFormatter = new JsonFormatter();
            }).CreateLogger();
```
Interesting thing is that when i try to run the given test cases in your provided repository it works fine but not in case of nuget package.

**Comment by steffenlyng** [comment]
@cognitive-arch @misky1986 @dorzeidman 
Thanks all for your feedback - I'll see if I can figure out what is going on, and hopefully find a solution for it.

**Comment by cognitive-arch** [comment]
Thanks @steffenlyng . Im trying to figure it out too. If i find the solution Ill share here too.

**Comment by steffenlyng** [comment]
@cognitive-arch I just tested with: https://gist.github.com/steffenlyng/609f91968cfbe7bd867b19fe5a0596b4

Serilog.Sinks.RabbitMq=3.0.6

**Comment by steffenlyng** [comment]
@misky1986 I have created a setup using RabbitMq 3.0.6 (nuget)

https://gist.github.com/steffenlyng/0a165bbfc4bfc0d6771d48a8d445cd72

I setup rabbitmq as follows:
0. Clean installation of rabbitmq (see above description in my answerr to @cognitive-arch )
1. I created a queue called `testqueue`
2. Add user called `rabbitmq-test-user`, with password: `rabbitmq-test-password`
3. I Added a permission for the user so it has access
4. I Ran the gist above

That worked. 

Can you try following these instructions ? And let me know.. :)

**Comment by cognitive-arch** [comment]
@steffenlyng Thanks again for the help.  Its working really fine as far as console application concern but not in asp.net core API project.

Here is the sample code with sink configuration and its not logging any error or information into queue . 

https://gist.github.com/cognitive-arch/e582fac189fc2fd8d26d4baf121c3e26

I dont know whats wrong with the  configuration.

**Comment by steffenlyng** [comment]
Based on your example, could you please try:

```
var loggerFactory = new LoggerFactory();
loggerFactory
  .AddSerilog(logger)
  .AddConsole(LogLevel.Information);
```

This worked for me, based on your example.

**Comment by steffenlyng** [comment]
@misky1986 I am closing this as it seems to be misconfiguration. Based on my trials of yours and @cognitive-arch scenarios I don't see any flaws. Only misinformation in documentation that I have now fixed. 

I've tested your examples, and they work.

Please let me know if you continue to experience problems.

**Comment by cognitive-arch** [comment]
@steffenlyng Thanks its working fine now. Problem was as you mentioned misinformation in documentation and my bad too I forgot the point you mentioned `Log.Logger`.
