### ISSUE TITLE
Dynamic routekey 

### ISSUE THREAD

**Issue by NicolaAtorino** [steffenlyng/serilog-sinks-rabbitmq#97]
Hello, I am trying to use the sink to write to different queues in RabbitMQ. One of the possibilities is to use a header o a topic exchange with a routing key. 

By going trough the readme i noticed that the routing key has to be set statically at startup. I would love the possibility of extrapolating this routekey from the event being logged itself in order to define where this message should go.

**Comment by cognitive-arch** [comment]
@NicolaAtorino  which version of the sink you're using. Because its latest version not logging any event into queue. Looking for help.

**Comment by steffenlyng** [comment]
@cognitive-arch Please write an issue that describes your problem. Thanks.

@NicolaAtorino I'd love to extend the library to take into account the feature you are looking for. But please write the issue based on the new feature template, so we have sufficient information.

**Comment by cognitive-arch** [comment]
@steffenlyng Thanks for your response. I have already described my problem in the open issue #91 . I need help I dont know whats wrong with the configuration.

**Comment by steffenlyng** [comment]
@NicolaAtorino I am closing this, and I await your feature request, if it is still relevant. 

**Please use the relevant template.**
